dremio:
  outputs:
    unmanaged:
      type: dremio
      threads: 2
      driver: "{{ env_var('DREMIO_DRIVER_PATH') }}"
      host: "{{ env_var('DREMIO_HOST') }}"
      port: "{{ env_var('DREMIO_PORT') | as_number }}"
      environment: "{{ env_var('DREMIO_ENVIRONMENT') }}"
      database: '@admin'
      schema: dbt
      user: "{{ env_var('DREMIO_USER') }}"
      password: "{{ env_var('DREMIO_PASSWORD') }}"
    managed:
      type: dremio
      threads: 2
      driver: "{{ env_var('DREMIO_DRIVER_PATH') }}"
      host: "{{ env_var('DREMIO_HOST') }}"
      port: "{{ env_var('DREMIO_PORT') | as_number }}"
      environment: "{{ env_var('DREMIO_ENVIRONMENT') }}"
      database: "{{ env_var('DREMIO_DATALAKE') }}"
      schema: ods
      user: "{{ env_var('DREMIO_USER') }}"
      password: "{{ env_var('DREMIO_PASSWORD') }}"
  target: unmanaged